### ISSUE TITLE
Mark forwarded messages as such

### ISSUE THREAD

**Issue by shirgoldbird** [pigpagnet/save-your-telegram-history#18]
Currently forwarded messages are not marked as such and only have the name of the person who forwarded the messages. They should instead have the name of the person who forwarded them, an indicator that the message was forwarded, and the name of the person who wrote the original message.

Awesome job on the extension, thanks so much for your hard work. :)

**Comment by vanchope** [comment]
Example of forwarded message:

```
Ivan P(you) [06.03.2017 22:55:00]
{{FWD: Telegram, 11.02.2017 23:22:09}}
Your login code: 111111
```
