### ISSUE TITLE
Seems not to work at all

### ISSUE THREAD

**Issue by LoneSnark** [pigpagnet/save-your-telegram-history#28]
Open the chat, open the extension, the clock runs but nothing ever comes from it. I have left it running in reasonably short chats for several minutes and nothing pops up, just the clock runs forever. 
![chrome extension](https://cloud.githubusercontent.com/assets/17257167/24615822/57108ed8-185d-11e7-81b2-a9414d75b8e5.png)

**Comment by minaporzamani** [comment]
Hi my telegram info

**Comment by LoneSnark** [comment]
Did you mean to send me your telegram info? I don't believe I see it

**Comment by LoneSnark** [comment]
My Chrome was out-of-date. Updating it has resolved this issue.

**Comment by aemxn** [comment]
I'm having the similar issue. I've updated my Chrome to Version 62.0.3202.89 (Official Build) (64-bit), but the problem is still there. Which version are you using @LoneSnark ?

**Comment by vanchope** [comment]
@aimanbaharum have you managed to get it running in the end? Maybe you can try these steps to solve the issue:
1. refreshing the telegram web-page,
2. reinstalling the extension,
3. restarting chrome,
4. inspecting what errors are shown in console logs (inspect web telegram page and inspect popup).
