### ISSUE TITLE
Calls break the extension

### ISSUE THREAD

**Issue by regeneron** [pigpagnet/save-your-telegram-history#35]
Hi, thanks for the great extension!

Unfortunately, this extension can only save messages until it reaches the first Telegram call information (such as "Missed Call"). After that, the timer keeps increasing, but nothing happens.

Thanks!

**Comment by vanchope** [comment]
The problem has been reported by other users as well. 

On December 31, 2017, Ciaran Deasy described this problem at the chrome webstore:

> I had trouble downloading one of my chats with this extension, and I discovered that it's getting stuck on a **"Missed Call"** in my history. I deleted that entry from the chat and the extension worked fine afterwards.
> 
> Letting you know so you can investigate and fix. It might explain why some other users aren't able to download their chats.

**Comment by vanchope** [comment]
Connected with #36

**Comment by vanchope** [comment]
Released in version 2.2.2.
