### ISSUE TITLE
The process crawls to a stop with very large conversations

### ISSUE THREAD

**Issue by Razpudding** [pigpagnet/save-your-telegram-history#7]
I've noticed the process gets slower and slower with big conversations. Mine now has a working time of ~2000ms after loading ~7000 messages. I think this is caused because all the messages and images are still loaded on the page.
If you add an option to once in a while delete all the content on the page (every couple thousand messages), while still having all the text in the popup window, it would be a lot faster to get through big conversations.

I'll try to make some adjustments myself.

**Comment by atenrok** [comment]
same here. I have ~2.5 years worth of messages mixed with images which I'm trying to backup. The extension either stops loading the messages half-way through or telegram-web crashes. I tried about 5 times already with the same outcome...  

Is there a hope?

**Comment by Razpudding** [comment]
@atenrok Theres definitely hope! I guess the simplest solution would be to run a js script simultaneously that deletes all the messages that have already been copied. That should keep the browser from crashing. That script could run every couple minutes.
I'm now working with the messages I've managed to download so far (I'm making a data visualization). If this plugin isn't updated by the time I'm finished with that I'll write the additional script myself.

**Comment by vanchope** [comment]
@Razpudding @atenrok  I have opened a new issue #8  for the new feature "bulk delete of messages". Could you meanwhile test a newer version (2.0.0)?

**Comment by atenrok** [comment]
Hey vanchope,

This new version is awesome! I have saved my 3-years worth of messages in
couple of clicks on +2000 button. You rock!

Thank you so much

PS: now I just need to find similar tool to save all the media from
Telegram log.

**Comment by Razpudding** [comment]
New version works like a charm! Loaded up ~19K messages in a couple minutes.
